/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');


class ztr_so_flow_demoService extends LCAPApplicationService {
    async init() {

      
        return super.init();
    }
}


module.exports = {
    ztr_so_flow_demoService
};